NEI <- readRDS("summarySCC_PM25.rds")
DATA<-subset(NEI,fips == "24510" | fips == "06037")
vehicles<-subset(DATA,type=="ON-ROAD")
x<-aggregate(vehicles$Emissions,by=list(year=vehicles$year,fips=vehicles$fips),FUN=sum)
x["fips"]<-c("Los Angeles","Los Angeles","Los Angeles","Los Angeles","Baltimore","Baltimore","Baltimore","Baltimore")
colnames(x)<-c("year","city","Emissions")
library(ggplot2)
qplot(year,Emissions,data=x,facets = .~city,color=city,geom=c("line"))
ggsave(filename="plot6.png")
