## Exploratory Data Analysis of the NOAA Storm Database  
**Reproducible Research Peer Assessment – Week 3**

### **Synopsis**

This report presents an exploratory data analysis using data from the U.S. National Oceanic and Atmospheric Administration (NOAA) Storm Database. This database tracks the characteristics of major storms and weather events in the United States, including when and where they occur, as well as their associated fatalities, injuries, and economic damages.

The motivation behind this analysis is rooted in the fact that severe weather events can pose serious risks to public health and result in substantial financial losses for communities. Understanding which event types have the greatest impact allows officials and emergency planners to implement more effective contingency strategies, with the ultimate goal of reducing the toll these events take when they inevitably happen again.

Since the dataset spans from 1950 to 2011, but earlier years are less complete, our analysis focuses on data from **2006 onward** to ensure greater reliability and consistency.

To streamline the analysis, we group related event types into broader categories. From this, we seek to answer two key questions:

1. **Which types of events are most harmful to population health?**  
2. **Which types of events have the greatest economic consequences?**

Our findings suggest that **events involving extreme cold or ice** have the most significant impact on both public health and the economy. Other categories, such as **heat or fire**, **water-related events (e.g., floods, tsunamis)**, and **wind/storm-related phenomena**, also contribute notably to injuries, fatalities, and damages, though to a lesser extent.

---

## Data Processing

This section outlines the data acquisition and preprocessing steps used for analyzing the NOAA Storm Database. The dataset was obtained via the [Reproducible Research course on Coursera](https://www.coursera.org/learn/reproducible-research), offered by the Johns Hopkins Bloomberg School of Public Health.

To begin, the data was downloaded and read into R using the following code:

```r
f <- tempfile()
download.file("http://d396qusza40orc.cloudfront.net/repdata/data/StormData.csv.bz2", f)
data <- read.csv(bzfile(f))
```

Since earlier entries in the database are less complete, our focus is on events from **2006 onward**. A regular expression is used to filter dates in the second column of the dataset, which contains date-time information:

```r
v <- grepl("20[0-1][6-9]", data[, 2])
dataSplit <- data[v, ]
```

Next, the `EVTYPE` column (event type) is reviewed and categorized into **eight major groups** based on related weather phenomena:

- **COLD/ICE**: Extreme winter or icy conditions  
- **HEAT**: High temperatures, drought, or fire-related events  
- **FOG**: All fog-related events  
- **WATER**: Floods, heavy rain, and water-related damage  
- **WIND/STORM**: Storms, tornadoes, hurricanes, and wind events  
- **LIGHTNING**: All lightning-related events (including common misspellings)  
- **VOLCANO/TSUNAMI**: Rare but high-impact volcanic or tsunami incidents  
- **DUST**: Dust storms and related phenomena

To build these groupings, character vectors are created containing keywords associated with each category. These vectors are uppercased to match the formatting in the dataset and include common spelling errors observed in the raw data.

```r
coldIceStrings <- toupper(c("avalanche", "avalance", "blizzard", "chill", "cold", 
  "cool", "glaze", "hypothermia", "hyperthermia", "ice", "icy", "freez", "frost", 
  "low temp", "sleet", "snow", "wint"))

heatStrings <- toupper(c("below normal precip", "dry", "drie", "drought", "fire", 
  "heat", "high temp", "hot", "warm"))

fogStrings <- toupper(c("fog", "vog"))

waterStrings <- toupper(c("coast", "cstl", "current", "dam fail", "dam break", 
  "drizzle", "drown", "erosion", "erosin", "flood", "floood", "fld", "heavy shower", 
  "high water", "high waves", "lake", "landslump", "marine", "precip", "rain", 
  "rising water", "river", "rogue wave", "slide", "stream", "sea", "seiche", 
  "surf", "swell", "tide", "tidal", "torrent", "wet"))

windStormStrings <- toupper(c("burst", "cloud", "depression", "floyd", "funnel", 
  "gust", "hail", "hurricane", "landspout", "storm", "southeast", "thunderstorm", 
  "thundertsorm", "thundestorm", "tornado", "torndao", "tstm", "turbulence", 
  "typhoon", "wall", "waterspout", "water spout", "wayterspout", "wind", "wnd"))

lighteningStrings <- toupper(c("lightning", "ligntning", "lighting"))

volcanoTsunamiStrings <- toupper(c("tsunami", "volcan"))

dustStrings <- toupper("dust")

disasterStrings <- c("COLD/ICE", "HEAT", "FOG", "WATER", 
                     "WIND/STORM", "LIGHTNING", 
                     "VOLCANO/TSUNAMI", "DUST")
```

These keyword lists form the foundation for reclassifying and analyzing the event types, ensuring consistency and meaningful aggregation in subsequent analyses.

---

Once this has been performed, we will append a new column to our data frame to allow for easier plotting using the ggplot2 system. What we will do is go through every single row of this data frame and determine what the disaster is. We will then check to see what category this particular disaster belongs to and assign a unique ID for the corresponding location in this column. We also use regular expressions to aid in this work. We will also create another column that stores the corresponding type of event (one of the 8 categories) in the next column after this appended data frame. Before we do this, after going through the above code, there will be some rows that are assigned a 0 ID. The reason why is because these events did not fall under any of the above catagories. The strings in these rows consisted of unrelated strings, such as SUMMARY. As such, we will choose to ignore these. We will filter out any rows that have an ID of 0. Once we do this, we will create the aforementioned column.

disasterIDs <- rep(0, nrow(dataSplit))
# Place a new column in the data frame that contains an ID of which disaster
# belongs to which catagory
for (i in 1:nrow(dataSplit)) {
    # Grab the disaster
    disaster <- dataSplit[i, "EVTYPE"]
    # Split string into spaces if applicable
    spt <- strsplit(as.character(disaster), " ")

    # For each space that we have, append a |
    spt <- spt[[1]]
    disasterString = c()
    for (j in 1:length(spt) - 1) {
        disasterString = c(spt[j], "|")
    }
    disasterString <- c(disasterString, spt[length(spt)])
    disaster <- paste(disasterString, collapse = "")

    # Check to see which one this belongs to
    if (any(grepl(disaster, coldIceStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 1
    } else if (any(grepl(disaster, heatStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 2
    } else if (any(grepl(disaster, fogStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 3
    } else if (any(grepl(disaster, waterStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 4
    } else if (any(grepl(disaster, windStormStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 5
    } else if (any(grepl(disaster, lighteningStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 6
    } else if (any(grepl(disaster, volcanoTsunamiStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 7
    } else if (any(grepl(disaster, dustStrings), na.rm = TRUE)) {
        disasterIDs[i] <- 8
    }
}
# Our appended data frame
dataSplitNew <- cbind(dataSplit, disasterIDs)
dataSplitNewFinal <- dataSplitNew[disasterIDs != 0, ]
disasterStringColumn <- disasterStrings[dataSplitNewFinal$disasterIDs]
dataSplitNewFinal <- cbind(dataSplitNewFinal, disasterStringColumn)
The last step we need is to evaluate economic damage performed for each kind of event. By examining the data, there are two columns of interest: PROPDMG and PROPDMGEXP. PROPDMG contains a base number, and PROPDMGEXP contains a single character that contains a multiplier of damage. This falls into one of three categories: K, M and B. K denotes thousands of dollars, M denotes millions of dollars and B denotes billions of dollars. As an example, supposing that a field of PROPDMG was 25.2, and PROPDMGEXP was M. This denotes that the total economic damage incurred for an event was $25.2 million dollars. As such, we will create a new column in our data frame that consists of the amount of damage incurred for a particular event in true form.

# Create a new column that appends the actual damage in numeric format
amountDollars <- rep(0, nrow(dataSplitNewFinal))
for (i in 1:nrow(dataSplitNewFinal)) {
    amount <- dataSplitNewFinal[i, "PROPDMG"]
    typ <- toupper(dataSplitNewFinal[i, "PROPDMGEXP"])

    if (typ == "K") {
        amountDollars[i] <- amount * 1000
    } else if (typ == "M") {
        amountDollars[i] <- amount * 1e+06
    } else if (typ == "B") {
        amountDollars[i] <- amount * 1e+09
    }
}

amountDollarsInBillions = amountDollars/1e+09
dataSplitNewAmounts <- cbind(dataSplitNewFinal, amountDollarsInBillions)
Results

We will now illustrate our results after all of the pre-processing performed on the data. We will show 3 bar charts.

The total number of fatalities from 2006 and onwards for each type of disaster
The total number of injuries from 2006 and onwards for each type of disaster
The total amount of economic damage from 2006 and onwards for each type of disaster
We use the ggplot2 graphing system - specifically qplot to illustrate our findings.

Plot #1 - Total number of fatalities

library(ggplot2)
qplot(disasterStringColumn, FATALITIES, data = dataSplitNewFinal, stat = "summary", 
    fun.y = "sum", geom = "bar", fill = factor(disasterStringColumn), main = "Total amount of fatalities (2006-2011)", 
    xlab = "Type of Disaster", ylab = "Amount of fatalities")
plot of chunk unnamed-chunk-5

Plot #2 - Total number of injuries

library(ggplot2)
qplot(disasterStringColumn, INJURIES, data = dataSplitNewFinal, stat = "summary", 
    fun.y = "sum", geom = "bar", fill = factor(disasterStringColumn), main = "Total number of injuries (2006-2011)", 
    xlab = "Type of Disaster", ylab = "Amount of injuries")
plot of chunk unnamed-chunk-6

Plot #3 - Total amount of economic damage

library(ggplot2)
qplot(disasterStringColumn, amountDollarsInBillions, data = dataSplitNewAmounts, 
    stat = "summary", fun.y = "sum", geom = "bar", fill = factor(disasterStringColumn), 
    main = "Total amount of economic damage (2006-2011)", xlab = "Type of Disaster", 
    ylab = "Total amount of damage (in billions of dollars)")
plot of chunk unnamed-chunk-7

Analysis

Plot #1 - Total number of fatalities

As can be seen in the plot, there is an overwhelming amount of fatalities from the last few years (2006 and onwards) that are specifically related to cold or ice related events. Events that dealt with lightening or volcano and tsunami related events did not appear within this year range and so they are not displayed here. The second most amount of fatalities is due to anything water related. This makes sense as some of the most severe hurricanes (Katrina as an example) happened within this range of years. The ones that come after heat related events are wind/storm events, followed by dust and fog related events. What is interesting is that cold and ice related events tend to be more predictable as the seasons experienced in certain areas of the United States are expected to fall between certain months. Even though we can prepare for these kinds of events, the amount of fatalities is still quite large. The difference between cold and ice events compared to water events (the second highest amount of fatalities) is well over 400.

Plot #2 - Total number of injuries

This more or less follows the same kind of trends as the first plot. Cold and ice related events are still rated at the highest (almost 6000 injuries) throughout this year range. However, the amount of water injuries was significantly less. This makes sense as fewer injuries are experienced by anything water related. It is quite unfortunate, but given the magnitude of water related events, very few survive to succumb to any injuries. The second highest amount of injuries experienced throughout this year range are anything related to heat, which is just under 2000. As such, the difference between cold and ice related events in comparison to heat related events is almost 4000. Wind and storm events are rated as third highest, followed by water, fog and dust related events.

Plot #3 - Total amount of economic damage

This is actually quite different from the other plots we have experienced. For one thing, ther is virtually no damage from dust and fog related events, which makes sense. Cold and ice related events still have the most highest amount of damange, ranging in almost $150 billion dollars worth throughout the range we have specified. The next amount is wind and storm related events, and is about $10 billion dollars worth. After comes water, then heat.
